// Gallery data — images & project titles (CS + EN)
window.GALLERIES = {
  rekonstrukce: [
    { folder: "mk-stavba", title: { cs: "Mariánská Kasárna, České Budějovice", en: "Mariánská Kasárna, České Budějovice" } },
    { folder: "Siroka-CK", title: { cs: "Penzion a kavárna Široká, Český Krumlov", en: "Široká Pension & Café, Český Krumlov" } },
    { folder: "oprava-fasady-matie-skolske", title: { cs: "Oprava fasády Matice Školské a Komenského ul., Č. Budějovice", en: "Facade renovation — Matice Školské & Komenského St., Č. Budějovice" } },
    { folder: "apartmany", title: { cs: "Residence u Černé věže, České Budějovice", en: "Black Tower Residence, České Budějovice" } },
    { folder: "panska_ck", title: { cs: "Residence Muzeum Vltavínů, Panská, Český Krumlov", en: "Moldavite Museum Residence, Panská, Český Krumlov" } },
    { folder: "muzeum-vltavinu-ck", title: { cs: "Muzeum Vltavínů, Panská, Český Krumlov", en: "Moldavite Museum, Panská, Český Krumlov" } },
    { folder: "rd-stejskal", title: { cs: "Muzeum cestopisné literatury Dr. Stejskala, Č. Budějovice", en: "Dr. Stejskal Travel Literature Museum, Č. Budějovice" } },
    { folder: "rd_smrhov", title: { cs: "Zemědělská usedlost Smrhov", en: "Smrhov Farmhouse" } },
    { folder: "atelier-kajov", title: { cs: "Atelier Kájov", en: "Atelier Kájov" } },
    { folder: "atelier-seidl", title: { cs: "Atelier Seidl, Český Krumlov", en: "Atelier Seidl, Český Krumlov" } },
    { folder: "sportcentrum-ruze", title: { cs: "Hotel Růže — Sportcentrum, Český Krumlov", en: "Hotel Růže — Sports Center, Český Krumlov" } },
    { folder: "psi-utulek", title: { cs: "Psí útulek, Český Krumlov", en: "Dog Shelter, Český Krumlov" } },
    { folder: "grand", title: { cs: "Hotel Grand, České Budějovice", en: "Hotel Grand, České Budějovice" } },
    { folder: "fasada-linecka", title: { cs: "Oprava fasády Linecká ul., Český Krumlov", en: "Facade renovation — Linecká St., Český Krumlov" } },
  ],
  novostavby: [
    { folder: "malce", title: { cs: "Obytné a rekreační zařízení Malče", en: "Malče Residential & Recreation Facility" } },
    { folder: "rd-konvalinkova", title: { cs: "Rodinný dům Konvalinková, Český Krumlov", en: "Konvalinková Family House, Český Krumlov" } },
    { folder: "keb-ege-provozni-budova", title: { cs: "KEB EGE Kájov — vestavba haly a provozní budova", en: "KEB EGE Kájov — hall fit-out & office building" } },
    { folder: "rd-vidov", title: { cs: "Rodinný dům Vidov", en: "Vidov Family House" } },
    { folder: "chlum-u-kremze", title: { cs: "Rodinný dům Chlum u Křemže", en: "Family House, Chlum u Křemže" } },
    { folder: "rodinny-dum-radostice", title: { cs: "Rodinný dům Radostice", en: "Radostice Family House" } },
    { folder: "rd-besednice", title: { cs: "Rodinný dům Besednice", en: "Besednice Family House" } },
  ],
  ocelove: [
    { folder: "brawe-hala", title: { cs: "Brawe Kaplice — hala", en: "Brawe Kaplice — hall" } },
    { folder: "brawe-expeidice", title: { cs: "Brawe Kaplice — expedice", en: "Brawe Kaplice — dispatch area" } },
    { folder: "keb-ege-hala", title: { cs: "KEB EGE Kájov — rozšíření haly", en: "KEB EGE Kájov — hall extension" } },
    { folder: "keb-ebe-kajov-vestavba", title: { cs: "KEB EGE Kájov — vestavba haly", en: "KEB EGE Kájov — hall fit-out" } },
    { folder: "keb-ege-svetllik", title: { cs: "KEB EGE Kájov — světlík", en: "KEB EGE Kájov — skylight" } },
    { folder: "Ege-cb-vestavek", title: { cs: "EGE Č. Budějovice — vestavek", en: "EGE Č. Budějovice — insert structure" } },
    { folder: "ege-vyroba", title: { cs: "Dílenská výroba", en: "Workshop fabrication" } },
    { folder: "radostice-schodiste", title: { cs: "Atypické konstrukce — RD Radostice", en: "Custom structures — Radostice house" } },
    { folder: "hala-vetrni", title: { cs: "Větřní — separační hala", en: "Větřní — separation hall" } },
    { folder: "rampa-fu-cb", title: { cs: "FÚ Č. Budějovice — bezbariérová rampa", en: "Tax Office Č. Budějovice — accessibility ramp" } },
  ],
  ostatni: [
    { folder: "dlazba_horni_ulice", title: { cs: "Zádlažba a inženýrské sítě Horní ulice, Č. Krumlov", en: "Paving & utilities, Horní St., Č. Krumlov" } },
    { folder: "zamkovka-ou", title: { cs: "Zámková dlažba OÚ Věžovatá Pláně", en: "Interlocking paving, Věžovatá Pláně town hall" } },
    { folder: "zamkovka-u-kostela", title: { cs: "Odseky u kostela, Věžovatá Pláně", en: "Granite setts near the church, Věžovatá Pláně" } },
  ],
};


window.GALLERY_IMAGES = {
  "mk-stavba": [
    "/images/galerie/mk-stavba/Marianska_Kasarna_1etapa-01-B (Medium).jpg",
    "/images/galerie/mk-stavba/Marianska_Kasarna_1etapa-04-B (Medium).jpg",
    "/images/galerie/mk-stavba/Č.Budějovice 019 (Custom).JPG",
    "/images/galerie/mk-stavba/Č.Budějovice 023 (Custom).JPG",
    "/images/galerie/mk-stavba/Č.Budějovice 055 (Custom).JPG",
    "/images/galerie/mk-stavba/Č.Budějovice 061 (Custom).JPG",
    "/images/galerie/mk-stavba/Marianska_Kasarna_1etapa-03-B (Medium).jpg",
    "/images/galerie/mk-stavba/Marianska_Kasarna_1etapa-09-B (Medium).jpg",
    "/images/galerie/mk-stavba/Marianska_Kasarna_1etapa-13-B (Medium).jpg",
    "/images/galerie/mk-stavba/Č.Budějovice 047 (Custom).JPG"
  ],
  "Siroka-CK": [
    "/images/galerie/Siroka-CK/IMG_1201 (Custom).jpg",
    "/images/galerie/Siroka-CK/Č.Krumlov 008 (Custom).JPG",
    "/images/galerie/Siroka-CK/IMG_1106 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1172malý (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1101 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1104 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1133 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1130 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1169 (Custom).jpg",
    "/images/galerie/Siroka-CK/IMG_1162 (Custom).jpg"
  ],
  "oprava-fasady-matie-skolske": [
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 074 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 073 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 066 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 078 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 077 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 076 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 084 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 088 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 086 (Custom).JPG",
    "/images/galerie/oprava-fasady-matie-skolske/Č.Budějovice 087 (Custom).JPG"
  ],
  "apartmany": [
    "/images/galerie/apartmany/Placheho20 (Medium).jpg",
    "/images/galerie/apartmany/ResidenceUCV-vstup (Medium).jpg",
    "/images/galerie/apartmany/The_House-1 (Medium).jpg",
    "/images/galerie/apartmany/The_House-2 (Medium).jpg",
    "/images/galerie/apartmany/Č.B. č.p.15,č.p.13 035 (Medium).jpg",
    "/images/galerie/apartmany/Č.B. č.p.15,č.p.13 005 (Medium).jpg",
    "/images/galerie/apartmany/Č.B. č.p.15,č.p.13 017 (Medium).jpg",
    "/images/galerie/apartmany/Č.B. č.p.15,č.p.13 020 (Medium).jpg",
    "/images/galerie/apartmany/Č.B. č.p.15,č.p.13 024 (Medium).jpg",
    "/images/galerie/apartmany/RUCV-Recepce (Medium).jpg"
  ],
  "panska_ck": [
    "/images/galerie/panska_ck/Muzeum-budova-HDR+okna (Medium).jpg",
    "/images/galerie/panska_ck/ap1-01 (Medium).jpg",
    "/images/galerie/panska_ck/ap2-03 (Medium).jpg",
    "/images/galerie/panska_ck/ap2-08 (Medium).jpg",
    "/images/galerie/panska_ck/ap3-3 (Medium).jpg",
    "/images/galerie/panska_ck/ap5-okno (Medium).jpg",
    "/images/galerie/panska_ck/ap5-pokoj2 (Medium).jpg",
    "/images/galerie/panska_ck/ap6-02 (Medium).jpg",
    "/images/galerie/panska_ck/ap6-08 (Medium).jpg",
    "/images/galerie/panska_ck/ap7-1 (Medium).jpg",
    "/images/galerie/panska_ck/IMG_4202 (Medium).jpg",
    "/images/galerie/panska_ck/IMG_4206 (Medium).jpg",
    "/images/galerie/panska_ck/IMG_3692 (Medium).JPG",
    "/images/galerie/panska_ck/IMG_3712 (Medium).JPG",
    "/images/galerie/panska_ck/IMG_3737 (Medium).JPG",
    "/images/galerie/panska_ck/IMG_5817 (Medium).jpg"
  ],
  "muzeum-vltavinu-ck": [
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_01-budova (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_02-Recepce (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_03-kino (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_04-hlavní_expozice (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_05-expozice-lupy (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_06-expozice-mteority+skla (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_07-expozice-mikroskopy (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_08-simulator_impaktu (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_10-expozice (Custom).jpg",
    "/images/galerie/muzeum-vltavinu-ck/Muzeum_11-expozice (Custom).jpg"
  ],
  "rd-stejskal": [
    "/images/galerie/rd-stejskal/IMG_5749-HDR (Medium).jpg",
    "/images/galerie/rd-stejskal/IMG_5754-HDR (Medium).jpg",
    "/images/galerie/rd-stejskal/IMG_5757-HDR (Medium).jpg",
    "/images/galerie/rd-stejskal/IMG_5765-HDR (Medium).jpg",
    "/images/galerie/rd-stejskal/IMG_5771-HDR (Medium).jpg"
  ],
  "rd_smrhov": [
    "/images/galerie/rd_smrhov/Smrhov 030 (Medium).JPG",
    "/images/galerie/rd_smrhov/Smrhov 029 (Medium).JPG",
    "/images/galerie/rd_smrhov/Smrhov 003 (Medium).JPG",
    "/images/galerie/rd_smrhov/Smrhov 007 (Medium).JPG"
  ],
  "atelier-kajov": [
    "/images/galerie/atelier-kajov/2012_1.20._ 101 (Custom).JPG",
    "/images/galerie/atelier-kajov/2012_1.20._ 098 (Custom).JPG",
    "/images/galerie/atelier-kajov/povltavska-31 (Custom).jpg",
    "/images/galerie/atelier-kajov/povltavska-32 (Custom).jpg",
    "/images/galerie/atelier-kajov/2012_1.20._ 108 (Custom).JPG",
    "/images/galerie/atelier-kajov/povltavska-33 (Custom).jpg",
    "/images/galerie/atelier-kajov/2012_10.2._ 079 (Custom).JPG",
    "/images/galerie/atelier-kajov/2012_6.9._ 001 (Custom).JPG",
    "/images/galerie/atelier-kajov/2012_10.2._ 080 (Custom).JPG",
    "/images/galerie/atelier-kajov/2012_10.2._ 083 (Custom).JPG"
  ],
  "atelier-seidl": [
    "/images/galerie/atelier-seidl/06205487 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06205515 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06205563 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06205647 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06164837 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06164949 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06175283 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06165263 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06165188 (2) (Custom).jpg",
    "/images/galerie/atelier-seidl/06205548 (2) (Custom).jpg"
  ],
  "sportcentrum-ruze": [
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 011 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 001 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 14 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 15 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 004 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 013 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum Růže 16 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum 19.3.10 006 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum 19.3.10 008 (Custom).JPG",
    "/images/galerie/sportcentrum-ruze/Sportcentrum 19.3.10 004 (Custom).JPG"
  ],
  "psi-utulek": [
    "/images/galerie/psi-utulek/100_0208 (Custom).JPG",
    "/images/galerie/psi-utulek/100_0078 (Custom).JPG",
    "/images/galerie/psi-utulek/100_0079 (Custom).JPG",
    "/images/galerie/psi-utulek/100_0083 (Custom).JPG",
    "/images/galerie/psi-utulek/100_0086 (Custom).JPG",
    "/images/galerie/psi-utulek/100_0211 (Custom).JPG",
    "/images/galerie/psi-utulek/Fotky Milan 011 (Custom).jpg",
    "/images/galerie/psi-utulek/Fotky Milan 017 (Custom).jpg",
    "/images/galerie/psi-utulek/Fotky Milan 021 (Custom).jpg",
    "/images/galerie/psi-utulek/Fotky Milan 054 (Custom).jpg"
  ],
  "grand": [
    "/images/galerie/grand/20.-10.2004 012 (Custom).jpg",
    "/images/galerie/grand/20.-10.2004 011 (Custom).jpg",
    "/images/galerie/grand/2004-07-29_00031 (Custom).JPG",
    "/images/galerie/grand/2004-05-17_00057 (Custom).jpg",
    "/images/galerie/grand/GRAND3 (Medium).jpg",
    "/images/galerie/grand/20.-10.2004 008 (Custom).jpg",
    "/images/galerie/grand/2004-07-22_00018 (Custom).JPG",
    "/images/galerie/grand/2004-07-28_00026 (Custom).JPG"
  ],
  "fasada-linecka": [
    "/images/galerie/fasada-linecka/Fasády Linecká 003 (Custom).JPG",
    "/images/galerie/fasada-linecka/Fasáda Linecká 011 (Custom).JPG",
    "/images/galerie/fasada-linecka/Fasáda Linecká 006 (Custom).JPG",
    "/images/galerie/fasada-linecka/Fasáda Linecká 007 (Custom).JPG"
  ],
  "malce": [
    "/images/galerie/malce/2013_3_4_Malče_0008 (Custom).jpg",
    "/images/galerie/malce/ORZ Malče jezero 003 (Custom).JPG",
    "/images/galerie/malce/ORZ Malče jezero 001 (Custom).JPG",
    "/images/galerie/malce/ORZ Malče jezero 010 (Custom).JPG",
    "/images/galerie/malce/povltavska-13 (Custom).jpg",
    "/images/galerie/malce/povltavska-20 (Custom).jpg",
    "/images/galerie/malce/povltavska-21 (Custom).jpg",
    "/images/galerie/malce/ORZ Malče 1-11 114 (Medium).JPG",
    "/images/galerie/malce/ORZ Malče 1-11 158 (Custom).JPG",
    "/images/galerie/malce/ORZ Malče 23.9.10 005 (Custom).JPG",
    "/images/galerie/malce/hriste/2014_1.21._Malče_ 014 (Custom).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 007 (Medium).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 009 (Medium).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 012 (Medium).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 014 (Medium).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 015 (Medium).JPG",
    "/images/galerie/malce/hriste/Malče hřiště 6-13 018 (Medium).JPG",
    "/images/galerie/malce/hriste/Hřiště Malče 005 (Custom).JPG",
    "/images/galerie/malce/hriste/Hřiště Malče 008 (Custom).JPG",
    "/images/galerie/malce/hriste/Hřiště Malče 013 (Custom).JPG"
  ],
  "rd-konvalinkova": [
    "/images/galerie/rd-konvalinkova/IMG_20151023_123540 (Custom).jpg",
    "/images/galerie/rd-konvalinkova/IMG_20151015_140439 (Custom).jpg",
    "/images/galerie/rd-konvalinkova/IMG_20151023_123604 (Custom).jpg",
    "/images/galerie/rd-konvalinkova/IMG_20151023_123519 (Custom).jpg",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 001 (Custom).JPG",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 002 (Custom).JPG",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 005 (Custom).JPG",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 007 (Custom).JPG",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 004 (Custom).JPG",
    "/images/galerie/rd-konvalinkova/Č.Krumlov 006 (Custom).JPG"
  ],
  "keb-ege-provozni-budova": [
    "/images/galerie/keb-ege-provozni-budova/5.5.2014 005 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/keb-ege 078 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/2014-03-11_00154 T (Custom).jpg",
    "/images/galerie/keb-ege-provozni-budova/2014-03-14_00197 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/2014-03-14_00191 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/2014-03-21_00242 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/KEB EGE 069 T (Custom).jpg",
    "/images/galerie/keb-ege-provozni-budova/keb-ege 093 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/keb-ege 087 (Custom).JPG",
    "/images/galerie/keb-ege-provozni-budova/keb-ege 089 (Custom).JPG"
  ],
  "rd-vidov": [
    "/images/galerie/rd-vidov/024 (Custom).JPG",
    "/images/galerie/rd-vidov/RD Vidov_5.6.2011 008 (Custom).JPG",
    "/images/galerie/rd-vidov/025 (Custom).JPG",
    "/images/galerie/rd-vidov/002 (Custom).JPG",
    "/images/galerie/rd-vidov/008 (Custom).JPG",
    "/images/galerie/rd-vidov/RD Vidov_5.6.2011 003 (Custom).JPG",
    "/images/galerie/rd-vidov/RD Vidov 10 (Custom).JPG",
    "/images/galerie/rd-vidov/PA150055 (Custom).JPG",
    "/images/galerie/rd-vidov/PA180073 (Custom).JPG",
    "/images/galerie/rd-vidov/PA260037 (Custom).JPG"
  ],
  "chlum-u-kremze": [
    "/images/galerie/chlum-u-kremze/2010-05-24_00120 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2010-05-24_00119 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2010-05-24_00117 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2010-04-22_00107 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-10-22_00081 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-10-09_00064 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-09-23_00048 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-09-23_00044 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-09-10_00034 (Custom).JPG",
    "/images/galerie/chlum-u-kremze/2009-09-01_00021 (Custom).JPG"
  ],
  "rodinny-dum-radostice": [
    "/images/galerie/rodinny-dum-radostice/DSCN4800 (Custom).JPG",
    "/images/galerie/rodinny-dum-radostice/RADOSTICE (Medium).jpg",
    "/images/galerie/rodinny-dum-radostice/RADOSTICE_1 (Medium).jpg",
    "/images/galerie/rodinny-dum-radostice/DSCN5245 (Custom).JPG",
    "/images/galerie/rodinny-dum-radostice/DSCN4904 (Custom).JPG",
    "/images/galerie/rodinny-dum-radostice/12 (Custom).JPG",
    "/images/galerie/rodinny-dum-radostice/Kámen PSS 018 (Custom).jpg",
    "/images/galerie/rodinny-dum-radostice/DSCN4920 (Custom).JPG",
    "/images/galerie/rodinny-dum-radostice/Radostice dokončeno 07 028 (Custom).jpg",
    "/images/galerie/rodinny-dum-radostice/Radostice dokončeno 07 049 (Custom).jpg"
  ],
  "rd-besednice": [
    "/images/galerie/rd-besednice/RD Besednice 2004- 009 (Medium).jpg",
    "/images/galerie/rd-besednice/4.RD Besednice (Custom).jpg",
    "/images/galerie/rd-besednice/2004-12-01_00107 (Custom).jpg",
    "/images/galerie/rd-besednice/2004-09-17_00089 (Custom).jpg",
    "/images/galerie/rd-besednice/2004-12-01_00096 (Custom).jpg",
    "/images/galerie/rd-besednice/2004-12-01_00101 (Custom).jpg",
    "/images/galerie/rd-besednice/2004-12-01_00099 (Custom).jpg",
    "/images/galerie/rd-besednice/2004-12-01_00264 (Custom).jpg",
    "/images/galerie/rd-besednice/RD Besednice 2004- 019 (Medium).jpg",
    "/images/galerie/rd-besednice/2004-09-02_00086 (Custom).jpg"
  ],
  "brawe-hala": [
    "/images/galerie/brawe-hala/20141022_103528 (Custom).jpg",
    "/images/galerie/brawe-hala/20141029_090445 (Custom).jpg",
    "/images/galerie/brawe-hala/20140918_143216 (Custom).jpg",
    "/images/galerie/brawe-hala/20140910_103925 (Custom).jpg",
    "/images/galerie/brawe-hala/7 (Custom).jpg",
    "/images/galerie/brawe-hala/20140923_162936 (Custom).jpg",
    "/images/galerie/brawe-hala/5 (Custom).jpg",
    "/images/galerie/brawe-hala/20140910_103650 (Custom).jpg",
    "/images/galerie/brawe-hala/20140910_093819 (Custom).jpg",
    "/images/galerie/brawe-hala/20140924_101456 (Custom).jpg"
  ],
  "keb-ege-hala": [
    "/images/galerie/keb-ege-hala/_MG_6268 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6267 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6276 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6270 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6255 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6253 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6256 (Medium).jpg",
    "/images/galerie/keb-ege-hala/_MG_6262 (Medium).jpg"
  ],
  "keb-ebe-kajov-vestavba": [
    "/images/galerie/keb-ebe-kajov-vestavba/2014-03-11_00154 T (Custom).jpg",
    "/images/galerie/keb-ebe-kajov-vestavba/2014-03-14_00195 T (Custom).jpg",
    "/images/galerie/keb-ebe-kajov-vestavba/2014-03-21_00242 (Custom).JPG",
    "/images/galerie/keb-ebe-kajov-vestavba/KEB EGE 069 T (Custom).jpg",
    "/images/galerie/keb-ebe-kajov-vestavba/keb-ege 008 (Custom).JPG",
    "/images/galerie/keb-ebe-kajov-vestavba/2014-03-14_00197 (Custom).JPG",
    "/images/galerie/keb-ebe-kajov-vestavba/2014-03-21_00259 (Custom).JPG",
    "/images/galerie/keb-ebe-kajov-vestavba/KEB EGE 057 T (Custom).jpg",
    "/images/galerie/keb-ebe-kajov-vestavba/KEB EGE 059 T (Custom).jpg"
  ],
  "keb-ege-svetllik": [
    "/images/galerie/keb-ege-svetllik/20150410_153738 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150410_155934 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150411_142852 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150411_143106 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150411_151123 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150411_162543 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150412_165827 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150413_103826 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150413_104024 (Custom).jpg",
    "/images/galerie/keb-ege-svetllik/20150416_084831 (Custom).jpg"
  ],
  "Ege-cb-vestavek": [
    "/images/galerie/Ege-cb-vestavek/20150804_093458 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_145458 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_103212 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_145436 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_093532 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_103232 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150804_093549 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150806_171018 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150808_082941 (Custom).jpg",
    "/images/galerie/Ege-cb-vestavek/20150808_093354 (Custom).jpg"
  ],
  "ege-vyroba": [
    "/images/galerie/ege-vyroba/20150417_065651 (Custom).jpg",
    "/images/galerie/ege-vyroba/20150417_065632 (Custom).jpg",
    "/images/galerie/ege-vyroba/20150417_081618 (Custom).jpg",
    "/images/galerie/ege-vyroba/20150417_065524 (Custom).jpg",
    "/images/galerie/ege-vyroba/26082011661 (Custom).jpg",
    "/images/galerie/ege-vyroba/20150417_065504 (Custom).jpg",
    "/images/galerie/ege-vyroba/20150417_065732 (Custom).jpg",
    "/images/galerie/ege-vyroba/Dílna + dvůr OK 013 (Custom).JPG",
    "/images/galerie/ege-vyroba/Dílna + dvůr OK 016 (Custom).JPG"
  ],
  "radostice-schodiste": [
    "/images/galerie/radostice-schodiste/5 (Custom).JPG",
    "/images/galerie/radostice-schodiste/7 (Custom).JPG",
    "/images/galerie/radostice-schodiste/6 (Custom).JPG",
    "/images/galerie/radostice-schodiste/8 (Custom).JPG",
    "/images/galerie/radostice-schodiste/10 (Custom).JPG",
    "/images/galerie/radostice-schodiste/PSS 003 (Custom).jpg",
    "/images/galerie/radostice-schodiste/DSCN4938 (Custom).JPG",
    "/images/galerie/radostice-schodiste/DSCN4939 (Custom).JPG",
    "/images/galerie/radostice-schodiste/DSCN4940 (Custom).JPG"
  ],
  "hala-vetrni": [
    "/images/galerie/hala-vetrni/obrázky 036 (Custom).jpg",
    "/images/galerie/hala-vetrni/obrázky 031 (Custom).jpg",
    "/images/galerie/hala-vetrni/obrázky 027 (Custom).jpg",
    "/images/galerie/hala-vetrni/obrázky 030 (Custom).jpg",
    "/images/galerie/hala-vetrni/obrázky 034 (Custom).jpg"
  ],
  "rampa-fu-cb": [
    "/images/galerie/rampa-fu-cb/20022012853 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012850 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012849 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012852 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012847 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012848 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012843 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/20022012842 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/12012012836 (Custom).jpg",
    "/images/galerie/rampa-fu-cb/12012012837 (Custom).jpg"
  ],
  "brawe-expeidice": [
    "/images/galerie/brawe-expeidice/20150324_130710 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150309_094240 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150309_094248 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150309_094302 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141745 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141603 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141814 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141622 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141804 (Custom).jpg",
    "/images/galerie/brawe-expeidice/20150227_141353 (Custom).jpg"
  ],
  "dlazba_horni_ulice": [
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 054 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 052 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 050 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 049 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 048 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 046 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 044 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 043 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 040 (Medium).jpg",
    "/images/galerie/dlazba_horni_ulice/Vánoce 2008 038 (Medium).jpg"
  ],
  "zamkovka-ou": [
    "/images/galerie/zamkovka-ou/IMG_20150702_083311 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083319 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083207 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083136 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083038 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083027 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083126 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083034 (Custom).jpg",
    "/images/galerie/zamkovka-ou/IMG_20150702_083147 (Custom).jpg"
  ],
  "zamkovka-u-kostela": [
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100437 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100632 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100415 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100347 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100628 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100546 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100529 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150527_140441 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150527_140454 (Custom).jpg",
    "/images/galerie/zamkovka-u-kostela/IMG_20150612_100603 (Custom).jpg"
  ],
};
